os: linux
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_API=28.0.3
  - NDK_API=21.0.6113669
  - REPO=t-e-l/termux-tasker
  - APK_NAME="TEL:Tasker"
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-${ANDROID_BUILD_API}
  - android-${ANDROID_API}
  - extra-android-m2repository
  - extra
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
  - android-ndk-license-.+
  - android-sdk-preview-license-.+
  - google-gdk-license-.+
before_cache: "-rm -f $HOME/.gradle/caches/modules-2/modules-2.lock -rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew :app:assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_c80f59e584b7_key -iv $encrypted_c80f59e584b7_iv -in keystore.jks.enc -out keystore.jks -d
- mkdir -p $ANDROID_HOME/licenses
- echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
- echo y | sdkmanager "platforms;android-${ANDROID_API}"
- echo y | sdkmanager "ndk-bundle"
- echo y | sdkmanager "ndk;${NDK_API}"
before_deploy:
- find . -name '*.apk'
- mv ./app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass
  $keystore_password -keypass $keystore_alias_password app-release.apk $keystore_alias
- jarsigner -verify app-release.apk
- "${ANDROID_HOME}build-tools/${ANDROID_BUILD_API}/zipalign -v 4 app-release.apk ${APK_NAME}.apk"

deploy:
  provider: releases
  api_key:
    secure: zLdMw4TABKogbI04JLSlqYgPlInL2kUQ0NiO4Ux2/A4KoaodSsjVEPh/eMfNIk/+RKdLzu1pQV9yMtpMJ8VJv4Mm+MkdOyv1Jgdd9sARV/P75x9w3J33tKWdjkzOmwLtiXivsfhEfFehm0oQj39B0WnVvDaeCFAYeIJYB1EuEQiRG+BKY0BAHnlGWQCGDDRm/r2xH+j6eLiJWtQpiE5TTiv4FeD42JLfNWTHxT3UKs2/spALeq8oGr0gAMOYixGEy7AuueVnYfCNJSpDD2TUOQKwXm5bZleduu9buMRrXiFwaLgrqaLoGkN6RzMWJSShIMLXF2sgpZKmH4KIDIShPwskqOj2VVXqgjYRWT0YdSPw2pgucxYX18VJgT9d1yvafXwwQlLABIboOTvltQQ/NQn0ltGtiaB2Oht2F/AAuJm5NVlMATxjjAUJsFhq//FVwDDA5VAeEe9ndfq5AptytEv6kaVvGGHt8f5VzSKKMtWxIA2z43Z+w/N6YG4+ViTw/z+L3KKM7ax2kJ3Epp/7HzBCe/YtM8kNVTTAo9BwYySFZD0yhv9r65OsdzgS9uUNX/Lk64Oo9avHEBE7glAq70iqC7E+gHoTM0zwCANBs7pkopnauSaCOb/9mGrzbdLfAs3NgtgV5wwC3FNLdtIMtcR2U9gwZYV6F1rkmUDeHYQ=
  file: ${APK_NAME}.apk
  skip_cleanup: true
  on:
    repo: ${REPO}
